apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: deconz
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: deconz
          servicePort: 32780
