apiVersion: v1
kind: Service
metadata:
  name: deconz
  labels:
    app: deconz
spec:
  ports:
  - port: 32780
    name: rest
  - port: 32783
    name: websockets
  clusterIP: None
  selector:
    app:  deconz
